window.data = {
    "name": "DB 2026",
    "matches": [
        {
            "num": 0,
            "team1": "bodo_ori",
            "team2": "Dariusbugs",
            "team3": "Masterozo",
            //"score": {"noPenalty": [50, 50, 20], "withPenalty": [40, 55, 66]},
            "score": {},
            "group": "Group A",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },
        {
            "num": 1,
            "team1": "anice5293",
            "team2": "SpeedWagon",
            "team3": "SilverPaper",
            "score": {},
            "group": "Group B",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },
        {
            "num": 2,
            "team1": "Paperforger",
            "team2": "Juan P Martinez",
            "team3": "huy nguyen",
            "score": {},
            "group": "Group C",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },
        {
            "num": 3,
            "team1": "Steve DC",
            "team2": "Zzilenunn",
            "team3": "al01780",
            "score": {},
            "group": "Group D",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 4,
            "team1": "Shapps__",
            "team2": "skyfoldspaper",
            "team3": "5mao5",
            "score": {},
            "group": "Group E",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 5,
            "team1": "anotherpapersmith",
            "team2": "PoLo",
            "team3": "andmet6",
            "score": {},
            "group": "Group F",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 6,
            "team1": "Paulorigami",
            "team2": "ayrton01981",
            "team3": "OrigummyNate",
            "score": {},
            "group": "Group G",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 7,
            "team1": "daydre4ming",
            "team2": "Nara.ori",
            "team3": "erlantrujillo_48211",
            "score": {},
            "group": "Group H",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 8,
            "team1": "Faraz",
            "team2": "T-DexParty",
            "team3": "ruska_08",
            "score": {},
            "group": "Group I",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 9,
            "team1": "maypel",
            "team2": "Ubu Roi",
            "team3": "colinperet",
            "score": {},
            "group": "Group J",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 10,
            "team1": "origamiforthewin",
            "team2": "Khoi",
            "team3": "Plop",
            "score": {},
            "group": "Group K",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 11,
            "team1": "ironik",
            "team2": "ldm291",
            "team3": "Sharigami",
            "score": {},
            "group": "Group L",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 12,
            "team1": "tankoda",
            "team2": "int_k0ng",
            "team3": "d3rpinator",
            "score": {},
            "group": "Group M",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 13,
            "team1": "Amurfalcon",
            "team2": "DavidOrigami",
            "team3": "Seal2324",
            "score": {},
            "group": "Group N",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 14,
            "team1": "Origamist01",
            "team2": "Doryuzu",
            "team3": "origamivan",
            "score": {},
            "group": "Group O",
            "start": "2026-07-17 00:00 UTC+2",
            "end": "2026-08-08 23:59 UTC+2",
        },{
            "num": 15,
            "team1": "Juan Flores C",
            "team2": "izzyoo",
            "team3": "flaxenpoet",
            "score": {},
            "group": "Group P",
            "start": "2026-08-13 00:00 UTC+2",
            "end": "2026-08-29 23:59 UTC+2",
        },
        {
            "num": 16,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 17,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 18,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 19,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 20,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 21,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 22,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 23,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 24,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 25,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 26,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 27,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 28,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 29,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        },{
            "num": 30,
            "team1": undefined,
            "team2": undefined,
            "score": {},
            "start": undefined,
            "end": undefined,
        }
    ]
};

window.abbreviations = {
    "bodo_ori": "bodo",
    "Dariusbugs": "Darius",
    "anice5293": "anice",
    "int__k0ng": "Casey",
    "erlantrujillo_48211": "erlantrujillo",
    "Nara.ori":"Nara",
    "daydre4ming": "reza",
    "izzyoo": "izzy",
    "Seal2324": "Seal",
    "Paulorigami": "Paul",
    "T DexParty": "T_Dex"
}